[tool.poetry]
name = "friendflix-server"
version = "0.1.0"
description = "Backend Flask server for friendflix"
authors = ["Ofer Sadan <ofersadan85@gmail.com>"]
readme = "../README.md"
license = "../LICENSE"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.1.1"
Flask-Cors = "^6.0.1"
Flask-JWT-Extended = "^4.7.1"
gunicorn = "^23.0.0"
httpx = "^0.28.1"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.1.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
pytest-watch = "^4.2.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
pytest-watch = "^4.2.0"
mypy = "^1.17.1"
types-psycopg2 = "^2.9.21.20250718"
types-flask-cors = "^6.0.0.20250520"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
addopts = "-vv" # --cov --cov-report=html"

[tool.mypy]
pretty = true
incremental = true
python_version = "3.12"
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
