[project]
name = "friendflix-backend"
description = "Backend server for friendflix"
authors = [{ name = "Ofer Sadan", email = "ofersadan85@gmail.com" }]
readme.file = "../README.md"
license.file = "../LICENSE"
version = "0.2.0"
requires-python = ">=3.13"

dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary,pool]>=3.3.4",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-watch>=4.2.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "I",
    "W",
    "E",
    "UP",
    "RUF",
]
ignore = []

[tool.ty.environment]
root = ["../"]

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
addopts = "-vv" # --cov --cov-report=html"
