[project]
name = "friendflix-backend"
description = "Backend server for friendflix"
authors = ["Ofer Sadan <ofersadan85@gmail.com>"]
readme = "../README.md"
license = "../LICENSE"
package-mode = false
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "bcrypt>=4.3.0",
    "fastapi[standard]>=0.116.1",
    "psycopg[binary,pool]>=3.2.9",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-watch>=4.2.0",
    "ruff>=0.12.7",
]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
addopts = "-vv" # --cov --cov-report=html"

[tool.mypy]
pretty = true
incremental = true
python_version = "3.13"
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
