DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL DEFAULT 'user'
);


DROP TABLE IF EXISTS credits;
CREATE TABLE IF NOT EXISTS credits (
    id INTEGER PRIMARY KEY NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    user_id TEXT NOT NULL UNIQUE,
    credits TEXT NOT NULL,
    Reason / action  TEXT NOT NULL
);



DROP TABLE IF EXISTS files_share;
CREATE TABLE IF NOT EXISTS files_share (
    id INTEGER PRIMARY KEY NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    shared_by TEXT NOT NULL UNIQUE,
    shared_with TEXT NOT NULL,
    file_id TEXT NOT NULL UNIQUE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


DROP TABLE IF EXISTS files;
CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
    expire TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
    description TEXT NOT NULL,
    owner TEXT NOT NULL UNIQUE,

);


