name: Backend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run backend tests with test DB scripts
        run: bash backend/scripts/run_tests_with_db.sh

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Ruff
        run: |
          uv tool install ruff
          uv tool install ty
      - name: Run Ruff formatter
        working-directory: backend
        run: uv tool run ruff check --output-format github
      - name: Install project dependencies
        working-directory: backend
        run: uv sync --locked
      - name: Run Ty type checker
        working-directory: backend
        run: uv tool run ty check --output-format github

  build-image:
    runs-on: ubuntu-latest
    needs: [tests, lints]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to the GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: | 
            ghcr.io/ofersadan85/friendflix-backend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build Docker image and push on version tags
        uses: docker/build-push-action@v7
        with:
          context: backend
          file: ./backend/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=backend-image
          cache-to: type=gha,mode=max,scope=backend-image
